### ISSUE TITLE
Host on GitHub Pages

### ISSUE THREAD

**Issue by zicklag** [foubian/cast2gif#1]
You should just have to enable the GitHub pages hosting for this site and it will work without any extra configuration. Then you can add the link to the repo description and readme.

**Comment by foubian** [comment]
as you see i'm a new github user i still explore all features and services thanks for your follow hope to keep contact with you

**Comment by foubian** [comment]
that's it you can share it if you found that it s a good solution
https://foubian.github.io/cast2gif/

**Comment by zicklag** [comment]
Great!

I haven't needed the functionality lately, but if I need it I'll probably be using yours. :)
